server:
   port: 8083
spring:
   application:
      name: booking-management
   data:
      mongodb:
         uri: mongodb+srv://alfayeed:abcd1234@cluster0.8nm7y.mongodb.net/flight_booking_system
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/flightauth
      username: root
      password: password
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true